Updated tests to cover fix for Issue #2 and deal with git ls-files base.  Improved testing to accommodate sorting, added diff when failed.

diff --git a/desktop-tools/test/srcfind/runtest b/desktop-tools/test/srcfind/runtest
--- a/desktop-tools/test/srcfind/runtest
+++ b/desktop-tools/test/srcfind/runtest
@@ -1,10 +1,5 @@
 #!/bin/zsh
 
-function prep() {
-	mkdir -p test_bed
-	(cd test_base ; cp -r . ../test_bed)
-}
-
 FAIL_CNT=0
 
 function run_test()
@@ -26,12 +21,13 @@ function run_test()
 			echo "$desc": OK
 	else
 		actual_fmt=$(echo "$actual" | sort)
-		expected_fmt=$(echo "$expected")
+		expected_fmt=$(echo "$expected" | sort)
 		if [ "$actual_fmt" = "$expected_fmt" ]
 		then
 			echo "$desc": OK
 		else
-			echo "$desc": 'FAIL - expected "'"$expected"'", got "'"$actual"'"'
+			echo "$desc": 'FAIL - expected "'"$expected_fmt"'", got "'"$actual_fmt"'"'
+			diff <(echo "$expected_fmt") <(echo "$actual_fmt")
 			rc=1
 		fi
 	fi
@@ -39,21 +35,21 @@ function run_test()
 	return $rc
 }
 
-prep
-
-cd test_bed
+cd test_base || { echo >&2 "missing directory 'test_base' - exiting"; exit 1; }
 
 run_test "Usage - no arguments (error)" 1 "" 
 run_test "Usage - end with flag (error)" 1 -S 
 
 run_test "Basic - 1 string, no matches (1 exit status)" 1 "" NOTHING
-run_test "Basic - 1 string, 1 file" 0 "./01.txt" hello
-run_test "Basic - 1 string, >1 file" 0 "./01.txt\n./02.txt" case
-run_test "Basic - 1 string, 1 file (case-sensitive default)" 0 "./02.txt" Case
-run_test "Basic - 1 string, >1 file (case-insensitive match with flag)" 0 "./01.txt\n./02.txt" -i Case
-run_test "Basic - 1 string, 1 file, show matches" 0 "./01.txt:Hello MIXED CASE" -S MIXED
+run_test "Basic - 1 string, 1 file" 0 "01.txt" hello
+run_test "Basic - 1 string, >1 file" 0 "01.txt\n02.txt" case
+run_test "Basic - 1 string, 1 file (case-sensitive default)" 0 "02.txt" Case
+run_test "Basic - 1 string, >1 file (case-insensitive match with flag)" 0 "01.txt\n02.txt" -i Case
+run_test "Basic - 1 string, 1 file, show matches" 0 "01.txt:Hello MIXED CASE" -S MIXED
 
-run_test "Simple - 2 strings in 1 file, separate lines" 0 "./01.txt" lower case
-run_test "Simple - filename with spaces" 0 "./a b c.txt" spacey
+run_test "Simple - 2 strings in 1 file, separate lines" 0 "01.txt" lower case
+run_test "Simple - filename with spaces" 0 "a b c.txt" spacey
+run_test "Simple - filename with spaces, show matches" 0 "a b c.txt:spacey file" -S spacey
+run_test "Simple - 1 string > 1 file, show matches (case insensitive)" 0 "01.txt:Hello MIXED CASE\n01.txt:Hello mixed case \n01.txt:hello lower case string\n02.txt:Case matters\n02.txt:case can matter\n02.txt:cases like this are difficult" -S -i case
 
 echo "Tests complete. Error count = $FAIL_CNT"
